---
title: "Les représentations victimales des violences de genre"
author: "Herbepin Emmanuel"
date: "2024-11-14"
output: html_document
theme : cerulean
editor_options: 
  chunk_output_type: console
---

```{r parameter, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center')
source("02_Scripts/03_Fonctions.R")
chut(source("02_Scripts/00_setup.R", echo = FALSE, verbose = FALSE))
chut(source("02_Scripts/01_Import.R", echo = FALSE, verbose = FALSE))
chut(source("02_Scripts/Recodage/01_Socio_Demo.R", echo = FALSE, verbose = FALSE))



DBf <- DB %>% vict()


```

```{r}
Basetemp$nbNA <- rowSums(is.na(Basetemp))
ggplot(Basetemp, aes(x = nbNA)) +
  geom_bar() +
  labs(title = "Nombre de valeurs manquantes par individu",
       x = "Nombre de valeurs manquantes",
       y = "Nombre d'individus")

Basetemp[Basetemp$nbNA > 2900,]
Basetemp$Vict <- rowSums(Basetemp[c(2934:2986,2990:3048,3051:3057)], na.rm = TRUE)
Basetemp$Vict <- rowSums(Basetemp[c(2934:2986,2993:3047,3051:3057)], na.rm = TRUE)
Basetemp[c("P_indicateur_12m":"FEnf_VensBISD")]

Basetemp$Vict[Basetemp$Vict == 0]

```

Travail sur les sifflements dans les espaces public

```{r}
Btp <- select(Basetemp, c("drague":"proagr", "ID")) 
Btp <- Btp[Btp$drague %in% c(
      "Une fois",
      "Quelques fois",
      "Souvent",
      "Presque toutes les semaines"
    ),]  #On enlèves les déclarations de non concerné, les non réponses et les refus (qui sont filtrés dans les questions suivantes)


#Vérification des filtres: 

filter(Btp, P1 == 1 & !is.na(P1aP), na.rm = TRUE)
filter(Btp, P1 %in% c(2,3,4) & !is.na(P1aS), na.rm = TRUE)
#On a une personne qui a répondu 2 (Quelques fois (2 à 5 fois) à P1 (avez-vous été sifflé-e, interpellé-e ou abordé-e sous un prétexte de drague) mais à qui on a posé la question de la gravité au singulier (P1aS) et qui a répondu 0 (pas grave). On va donc transposer sa réponse de P1aS à P1aP en supposant que l'erreur ne vient pas de la déclaration de violence mais de l'enquêteur qui a posé la mauvaise question.
Basetemp$P1aP[Basetemp$ID== 1001420599] <- 0
Basetemp$P1aS[Basetemp$ID== 1001420599] <- NA

filter(Btp, !(P1c %in% c(1,2)) & !is.na(P1c3), na.rm = TRUE)
filter(Btp, P1c %in% c(1,2) & is.na(P1c3), na.rm = TRUE) # Le filtre de P1c3 est respecté

filter(Btp, !(P1c %in% c(3,4,5,6)) & !is.na(P1c4), na.rm = TRUE)
filter(Btp, P1c %in% c(3,4,5,6) & is.na(P1c4), na.rm = TRUE)
# Une personne a répondu aux deux versions de la question P1c3 et P1c4. 
Basetemp$P1c4[Basetemp$ID== 1002126508] <- NA

filter(Btp, !(P1 %in% c(1,2,3,4)) & !is.na(P1d), na.rm = TRUE)
filter(Btp, (P1 %in% c(1,2,3,4)) & is.na(P1d), na.rm = TRUE) # Le filtre de P1d est respecté

filter(Btp, !(P1d == 4) & !is.na(P1d1), na.rm = TRUE)
filter(Btp, (P1d == 4) & is.na(P1d1), na.rm = TRUE) # Le filtre de P1d1 est respecté

table(Btp$P1)
res_ACM <- MCA(select(Btp, -c("ID")), ncp=6, graph=F) # On réalise l'ACM
explor(res_ACM)

DB$P1 %>% table(DB$P2,.)
t=. %>% table(DB$P1,.)
```

Exemples de traitements

```{r}
t(table(filter(PC18, PC18$AGE <= 30))) %>%
  kable(caption = "<center>Effectif par age</center>") %>%
kable_styling(bootstrap_options = c("striped", "hover"))



PC18_30 %>% 
  summarise_all(funs(sum(!is.na(.)))) %>%
  gather() %>%
  arrange(value) %>%
  kable(caption = "<center>Nombre de réponses par variable</center>",
         col.names = c("Variable", "Nombre de réponses")) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))%>%
  scroll_box(width = "100%", height = "500px")

ggplot(Basetemp, aes(x = Q16)) +
  geom_bar(width = 10) + 
  xlim(0, 500)

table(DB$sexe, DB$TypeEmp)

DB$TypeEmp %>%
  table(DB$sexe,.)
```

```{r}

DB %<>% mutate(
  EPlist = pmap(select(., paste0("P", 1:11)), c),#liste des réponses aux questions P1 à P11
  EP_div = as.numeric(map(EPlist, function(x) {
    return(length(x[!(x %in% c("0", "88", "99"))]))})), #Diversité des violences subies
  EP_div_rec = ifelse(EP_div>=2,"2+",EP_div),
  EP_fr_rec = as.numeric(map(EPlist, function(x) {
    x <- c(x[x != "0"],"0") #Supprime les "0"
    
    if (sum(x == "1", na.rm = TRUE) >= 3) { #Les individus qui ont déclaré exactement avoir subit 1 fois deux violences différentes sont considérés comme ayant subit 1 seule violence (il y en a 34)
      x <- c(x, rep("2",sum(x == "1", na.rm = TRUE) %/% 3)) #Ajoute un 2 pour chaque groupe de 3 "1"
      x <- x[x != "1"] #Supprime les "1"
    }
    
    if (sum(x == "2", na.rm = TRUE) >= 2) {
      x <- c(x, rep("3",sum(x == "2", na.rm = TRUE) %/% 2)) #Ajoute un 3 pour chaque groupe de 2 "2"
      x <- x[x != "2"] #Supprime les "2"
    }
    
    if (sum(x == "3", na.rm = TRUE) >= 2) {
      x <- c(x, rep("4",sum(x == "3", na.rm = TRUE) %/% 2)) #Ajoute un 4 pour chaque groupe de 3 "3"
      x <- x[x != "3"] #Supprime les "3"
    }
    
    return(max(x[x<5]))
  })),
  EP_dic = ifelse(EP_fr_rec==0,0,1),
  EP_fr_rec = factor(EP_fr_rec, levels = 0:4, labels = c("Non concerné", "Une fois", "Quelques fois", "Souvent", "un fois par mois ou plus")))
#EP_fr_rec est une fréquence recomposée des violences subies dans l'année dans l'espace public

freq(DB$EP_fr_rec)
cprop(table(DB$EP_dic, DB$sexe))
cprop(table(DB$EP_fr_rec, DB$sexe))

cprop(table(DB$EP_fr_rec, DB$sexe)[-1,], digits = 2) #Parmis les personnes qui ont subis des violences


DB %<>% mutate(
  EP_grav = pmap(select(., c(paste0("P", 1:9, "aS"),
                              paste0("P", 1:9, "aP"),
                              paste0("P", 10:11, "dS"),
                              paste0("P", 10:11, "dP"))), c), #liste des réponses aux questions P1 à P11
  EP_grav_max = as.character(map(EP_grav, function(x) {
    return(case_when(
    "2" %in% x | "1" %in% x[grepl("P$", names(x))] ~ "Très grave",
    "3" %in% x ~ "Assez grave",
    "0" %in% x ~ "Pas grave",
    TRUE ~ NA_character_))})),# Donne la gravité maximale subie
  
  
  #sommer si x in c(1,2) & names(x) ends with "P$"
  # ou x in c(2) & names(x) ends with "S$"
  
  EP_grav_nb = ifelse(is.na(EP_grav_max), NA,
                          as.character(map(EP_grav, function(x) {
    return(sum(x %in% c("1", "2", "3"), 
               na.rm = TRUE))}))),
  # Donne le nombre de violences grave subies ("au moins assez grave")
  
  EP_grav_tg_nb = ifelse(is.na(EP_grav_max), NA,
                        as.character(map(EP_grav, function(x) {
     return(sum((x %in% c("2"))|(x %in% c("1") & str_ends(names(x), "P")), # la modalité 1 pour les var qui finissent pas S n'existe pas, mais par sécurité et pour la reproduction dans d'autres domaines, on garde cette vérification
                na.rm = TRUE))}))), 
  # Donne le nombre de type de violences "très grave" subies
  
  EP_grav_ag_nb = ifelse(is.na(EP_grav_max), NA,
                        as.character(map(EP_grav, function(x) {
     return(sum((x %in% c("3")), 
                na.rm = TRUE))}))), 
  # Donne le nombre de type de violences "assez grave" subies
  
  EP_grav_pg_nb = ifelse(is.na(EP_grav_max), NA,
                        as.character(map(EP_grav, function(x) {
     return(sum((x %in% c("0")), 
                na.rm = TRUE))}))))



  # Donne le nombre de type de violences "pas grave" subies


  
  EP_grav_prop = 100 * as.numeric(DB$EP_grav_nb)/as.numeric(DB$EP_div),
  
  EP_tres_grav_nb = ifelse(is.na(EP_grav_max), NA,
                           as.character(map(EP_grav, function(x) {
    return(sum(x %in% c("2", "1"), na.rm = TRUE))}))), # Donne le nombre de violences "très grave" subies
  
  EP_tres_grav_prop = 100 * as.numeric(DB$EP_tres_grav_nb)/as.numeric(DB$EP_div)
  )

DB %>%
  select(EP_fr_rec, EP_grav_tg_nb) %>%
  mutate(EP_grav_tg_nb = ifelse(EP_grav_tg_nb>=1, 1,0)) %>%
  table() %>%
  lprop(digits = 2) 
# Proportion d'individus ayant déclaré avoir subi au moins une violence très grave en fonction du nombre de violences subies dans l'année

DB %>%
  select(EP_fr_rec, EP_grav_ag_nb) %>%
  mutate(EP_grav_ag_nb = ifelse(EP_grav_ag_nb>=2, "2+",EP_grav_ag_nb)) %>%
  table() %>%
  lprop(digits = 2) 

tbl =DB %>%
  select(EP_fr_rec, EP_grav_ag_nb) %>%
  mutate(EP_grav_ag_nb = ifelse(EP_grav_ag_nb>=1, "Oui", "Non")) %>%
  table() %>%
  lprop(digits = 2)

write.csv(tbl, "EP_grav_ag_nb.csv")
tbl %>%
ggplot() +
  geom_col(aes(x= Oui)) +
  labs(title = "Proportion de violences graves parmis les violences subies",
       x = "Proportion de violences graves subies",
       y = "Proportionn d'individus",
       caption = "Source: Enquête Virage
       Lecture :")

DB %>%
  group_by(sexe) %>%
  select(EP_fr_rec, EP_grav_tg_nb) %>%
  table()
%>%
  lprop(digits = 2) #Nombre de violences déclarées comme "au moins assez grave" par sexe 


ggplot() +
  aes(x = DB$EP_grav_prop) +
  geom_bar(aes(y = after_stat(prop * 100),fill = DB$sexe), position = "dodge") +
  labs(title = "Proportion de violences graves parmis les violences subies",
       x = "Proportion de violences graves subies",
       y = "Proportionn d'individus",
       caption = "Source: Enquête Virage
       Lecture : ~60% des hommes victimes de violences dans les espaces publics ne considèrent pas celles qu'ils ont subies comme graves. ~6% considèrent que seule la moitié est au moins 'assez grave'")


```








